(() => {
  const fairPrice = "https://www.fairprice.com.sg";
  const product = (path) => `${fairPrice}${path}`;
  const search = (query) => `${fairPrice}/search?query=${encodeURIComponent(query)}`;

  window.nakoIngredientCatalog = Object.freeze({
    "chicken-tender": { file: "chicken-tender.jpg", source: product("/product/master-grocer-99-fat-free-chicken-tenderloin-250g-chilled-250-g-90175216"), target: "Raw chicken tenderloin in a chilled supermarket pack" },
    "chicken-minced": { file: "chicken-minced.jpg", source: product("/product/kee-song-fresh-chicken-minced-300g-13097678"), target: "Fresh minced chicken in a labelled supermarket tray" },
    "chicken-breast": { file: "chicken-breast.jpg", source: product("/product/aw-s-market-kampong-chicken-breast-fillet-cube-300-g-90125965"), target: "Raw skinless chicken breast in a chilled supermarket pack" },
    "chicken-thigh": { file: "chicken-thigh.jpg", source: product("/product/farmfresh-chicken-leg-boneless-cube-250-g-90199908"), target: "Raw boneless chicken thigh in a chilled supermarket pack" },
    "chicken-wings": { file: null, source: null, target: "Raw chicken wings in a chilled supermarket pack" },
    pumpkin: { file: "pumpkin.jpg", source: product("/product/orgo-fresh-pumpkin-whole-pumkin-1-pc-90145601"), target: "Whole fresh pumpkin" },
    carrot: { file: "carrot.jpg", source: product("/product/snackables-snack-fresh-carrots-250g-13280574"), target: "Fresh whole carrots" },
    whitefish: { file: "whitefish.jpg", source: product("/product/catch-seafood-pacific-dory-fillet"), target: "Plain frozen dory / white-fish fillet package" },
    "sweet-potato": { file: "sweet-potato.jpg", source: product("/product/13135134"), target: "Fresh sweet potatoes" },
    zucchini: { file: "zucchini.jpg", source: product("/product/thygrace-green-zucchini-2-per-pack-13183890"), target: "Fresh green zucchini" },
    "napa-cabbage": { file: "napa-cabbage.jpg", source: product("/product/wa-wa-chye-baby-wongbok-250g-10950392"), target: "Whole wong bok / napa cabbage" },
    broccoli: { file: "broccoli.jpg", source: product("/product/orgo-fresh-royal-broccoli-280-g-90153099"), target: "Fresh broccoli head or supermarket pack" },
    rice: { file: "rice.jpg", source: product("/product/fairprice-japonica-rice-premium-short-grain-25kg-13086207"), target: "Japanese-style short-grain rice bag" },
    "soy-sauce": { file: "soy-sauce.jpg", source: product("/product/12400028"), target: "Japanese-style soy sauce bottle" },
    mirin: { file: "mirin.jpg", source: product("/product/takara-mirin-japanese-sweet-cooking-rice-wine-300ml-90002289"), target: "Mirin bottle" },
    "cooking-sake": { file: "cooking-sake.jpg", source: product("/product/kirei-premium-hinode-japan-ryorishu-cooking-sake-400-ml-90121995"), target: "Japanese cooking-sake bottle" },
    sugar: { file: "sugar.jpg", source: product("/product/fairprice-pure-cane-sugar-fine-grain-3kg-13179180"), target: "White-sugar packet" },
    honey: { file: null, source: null, target: "Honey bottle or jar" },
    matcha: { file: null, source: null, target: "Matcha powder tin" },
    milk: { file: null, source: null, target: "Fresh milk bottle" },
    ginger: { file: "ginger.jpg", source: product("/product/orgo-fresh-ginger-210-g-90160216"), target: "Fresh ginger root" },
    oil: { file: "oil.png", source: null, target: "Premium bottle of extra virgin olive oil" },
    sesame: { file: "sesame.jpg", source: product("/product/pasar-white-sesame-seed-150g-13218883"), target: "White sesame seed packet" },
    "salmon-fillet": { file: "salmon.jpg", source: product("/product/catch-seafood-atlantic-salmon-fillet-1-3-kg-90122048"), target: "Raw salmon fillet package" },
    salt: { file: "salt.jpg", source: product("/product/fairprice-premium-fine-salt-500g-432823"), target: "Ordinary table-salt packet" },
    eggs: { file: "egg.jpg", source: product("/product/pasar-fresh-eggs-30-per-pack-13197730"), target: "Fresh egg carton" },
    "knorr-quick-serve-macaroni": { file: null, source: "https://www.fairprice.com.sg/product/knorr-japanese-pork-bone-quick-serve-macaroni-bundle-of-4", target: "Knorr Quick Serve Macaroni packet; check for chicken flavour" },
    ham: { file: null, source: null, target: "Ready-to-eat sliced ham" },
    "fresh-chilli": { file: null, source: null, target: "Fresh red or green chillies" },
    "spring-onion": { file: null, source: null, target: "Fresh spring onion stalks" },
    spinach: { file: "spinach.jpg", source: product("/product/kok-fah-baby-spinach-200g-13032623"), target: "Fresh spinach pack" },
    lemon: { file: "lemon.jpg", source: product("/product/freshco-lemons-fresh"), target: "Fresh lemons" },
    pork: { file: "pork.jpg", source: product("/product/simply-yumme-pork-lean-slice"), target: "Lean raw pork slices in a labelled pack" },
    "pork-shoulder": { file: null, source: null, target: "Pork shoulder butt slices" },
    "pork-loin": { file: null, source: null, target: "Thick-cut pork loin chops" },
    cabbage: { file: "cabbage.jpg", source: product("/product/orgo-fresh-cabbage-whole-1-pc-90150967"), target: "Ordinary whole green cabbage" },
    "shimeji-mushroom": { file: "shimeji-mushroom.jpg", source: product("/product/hokto-mushroom-white-shimeiji-100g-11017131"), target: "Shimeji mushroom retail pack" },
    "button-mushroom": { file: "button-mushroom.jpg", source: product("/product/pasar-white-button-mushroom-200g-13101275"), target: "White button mushroom retail pack" },
    "enoki-mushroom": { file: null, source: null, target: "Fresh enoki mushroom pack" },
    dashi: { file: "dashi.jpg", source: product("/product/ajinomoto-hon-dashi-kirei-1-kg-90155858"), target: "Japanese dashi stock packet" },
    tuna: { file: "tuna.jpg", source: product("/product/fairprice-tuna-flakes-in-water-160g-13256630"), target: "Canned tuna in water" },
    tofu: { file: "firm-tofu.jpg", source: product("/product/fairprice-tau-kwa-2s-400g-13233989"), target: "Firm tofu in refrigerated retail packaging" },
    cucumber: { file: "cucumber.jpg", source: product("/product/malaysia-naturally-fresh-japanese-cucumber-400g-13097478"), target: "Fresh Japanese cucumber" },
    "sesame-oil": { file: "sesame-oil.jpg", source: product("/product/lee-kum-kee-pure-sesame-oil-207ml-13160717"), target: "Sesame-oil bottle" },
    "rice-vinegar": { file: "rice-vinegar.jpg", source: product("/product/redman-rice-vinegar"), target: "Rice-vinegar bottle" },
    miso: { file: "miso-paste.jpg", source: product("/product/kirei-yamataka-omiso-ya-san-japanese-shiro-miso-paste-1-kg-90085339"), target: "Japanese miso tub or pouch" },
    water: { file: "water.png", source: null, target: "A clean glass of water" },
    apple: { file: null, source: null, target: "Fresh apple" },
    bread: { file: null, source: null, target: "Sliced sandwich bread" },
    "peanut-butter": { file: null, source: null, target: "Peanut butter jar" },
    "strawberry-jam": { file: null, source: null, target: "Strawberry jam jar" },
    banana: { file: null, source: null, target: "Fresh banana" },
    mayonnaise: { file: null, source: null, target: "Mayonnaise bottle" },
    dashi: { file: "dashi.jpg", source: product("/product/ajinomoto-hon-dashi-kirei-1-kg-90155858"), target: "Japanese dashi stock packet" },
    tuna: { file: "tuna.jpg", source: product("/product/fairprice-tuna-flakes-in-water-160g-13256630"), target: "Canned tuna in water" },
    tofu: { file: "firm-tofu.jpg", source: product("/product/fairprice-tau-kwa-2s-400g-13233989"), target: "Firm tofu in refrigerated retail packaging" },
    cucumber: { file: "cucumber.jpg", source: product("/product/malaysia-naturally-fresh-japanese-cucumber-400g-13097478"), target: "Fresh Japanese cucumber" },
    "sesame-oil": { file: "sesame-oil.jpg", source: product("/product/lee-kum-kee-pure-sesame-oil-207ml-13160717"), target: "Sesame-oil bottle" },
    "rice-vinegar": { file: "rice-vinegar.jpg", source: product("/product/redman-rice-vinegar"), target: "Rice-vinegar bottle" },
    miso: { file: "miso-paste.jpg", source: product("/product/kirei-yamataka-omiso-ya-san-japanese-shiro-miso-paste-1-kg-90085339"), target: "Japanese miso tub or pouch" },
    water: { file: "water.png", source: null, target: "A clean glass of water" },
    apple: { file: null, source: null, target: "Fresh apple" },
    bread: { file: null, source: null, target: "Sliced sandwich bread" },
    "peanut-butter": { file: null, source: null, target: "Peanut butter jar" },
    "strawberry-jam": { file: null, source: null, target: "Strawberry jam jar" },
    banana: { file: null, source: null, target: "Fresh banana" },
    mayonnaise: { file: null, source: null, target: "Mayonnaise bottle" },
    "pork-ribs": { file: null, source: null, target: "Raw pork ribs" },
    "bak-kut-teh-spices": { file: null, source: null, target: "Bak kut teh spice packet" },
    garlic: { file: null, source: null, target: "Fresh garlic bulb" },
    "garlic-pepper": { file: null, source: null, target: "Garlic pepper seasoning bottle" },
    "potato-starch": { file: null, source: null, target: "Potato starch packet" },
    "dashi-soy-sauce": { file: null, source: null, target: "Japanese dashi soy sauce bottle" },
    "dark-soy-sauce": { file: null, source: null, target: "Dark soy sauce bottle" },
    nori: { file: null, source: null, target: "Nori seaweed sheets packet" },
    beef: { file: null, source: null, target: "Minced beef or sliced beef packet" },
    "crab-stick": { file: null, source: null, target: "Crab sticks / surimi package" },
    "wagyu-steak": { file: null, source: null, target: "Wagyu steak package (chilled/frozen)" },
    "black-pepper": { file: null, source: null, target: "Black pepper grinder or shaker bottle" },
    potato: { file: null, source: null, target: "Fresh whole potatoes" },
    "japanese-curry-blocks": { file: null, source: null, target: "Japanese curry roux block packet" },
    "king-oyster-mushroom": { file: null, source: null, target: "Fresh king oyster mushroom pack" },
    "cherry-tomatoes": { file: null, source: null, target: "Fresh cherry tomatoes punnet" },
    "chilli-powder": { file: null, source: null, target: "Chilli powder bottle or shaker" }
  });
})();
