(() => {
  const fairPrice = "https://www.fairprice.com.sg";
  const product = (path) => `${fairPrice}${path}`;
  const search = (query) => `${fairPrice}/search?query=${encodeURIComponent(query)}`;

  window.nakoIngredientCatalog = Object.freeze({
    "chicken-tender": { file: "chicken-tender.jpg", source: product("/product/master-grocer-99-fat-free-chicken-tenderloin-250g-chilled-250-g-90175216"), target: "Raw chicken tenderloin in a chilled supermarket pack" },
    "chicken-minced": { file: "chicken-minced.jpg", source: product("/product/kee-song-fresh-chicken-minced-300g-13097678"), target: "Fresh minced chicken in a labelled supermarket tray" },
    "chicken-breast": { file: "chicken-breast.jpg", source: product("/product/aw-s-market-kampong-chicken-breast-fillet-cube-300-g-90125965"), target: "Raw skinless chicken breast in a chilled supermarket pack" },
    "chicken-thigh": { file: "chicken-thigh.jpg", source: product("/product/farmfresh-chicken-leg-boneless-cube-250-g-90199908"), target: "Raw boneless chicken thigh in a chilled supermarket pack" },
    "chicken-wings": { file: null, source: search("fresh chicken wings"), target: "Raw chicken wings in a chilled supermarket pack" },
    pumpkin: { file: "pumpkin.jpg", source: product("/product/orgo-fresh-pumpkin-whole-pumkin-1-pc-90145601"), target: "Whole fresh pumpkin" },
    carrot: { file: "carrot.jpg", source: product("/product/snackables-snack-fresh-carrots-250g-13280574"), target: "Fresh whole carrots" },
    whitefish: { file: "whitefish.jpg", source: product("/product/catch-seafood-pacific-dory-fillet"), target: "Plain frozen dory / white-fish fillet package" },
    "sweet-potato": { file: "sweet-potato.jpg", source: product("/product/13135134"), target: "Fresh sweet potatoes" },
    "daikon-radish": { file: null, source: product("/product/japan-daikon-white-radish-500g-13103250"), target: "Fresh whole daikon radish" },
    tomato: { file: null, source: search("fresh tomato"), target: "Fresh whole tomatoes" },
    zucchini: { file: "zucchini.jpg", source: product("/product/thygrace-green-zucchini-2-per-pack-13183890"), target: "Fresh green zucchini" },
    "napa-cabbage": { file: "napa-cabbage.jpg", source: product("/product/wa-wa-chye-baby-wongbok-250g-10950392"), target: "Whole wong bok / napa cabbage" },
    broccoli: { file: "broccoli.jpg", source: product("/product/orgo-fresh-royal-broccoli-280-g-90153099"), target: "Fresh broccoli head or supermarket pack" },
    "steak-pepper": { file: null, source: product("/product/10351373"), target: "Steak-pepper seasoning packet" },
    rice: { file: "rice.jpg", source: product("/product/fairprice-japonica-rice-premium-short-grain-25kg-13086207"), target: "Japanese-style short-grain rice bag" },
    "soy-sauce": { file: "soy-sauce.jpg", source: product("/product/12400028"), target: "Japanese-style soy sauce bottle" },
    mirin: { file: "mirin.jpg", source: product("/product/takara-mirin-japanese-sweet-cooking-rice-wine-300ml-90002289"), target: "Mirin bottle" },
    "cooking-sake": { file: "cooking-sake.jpg", source: product("/product/kirei-premium-hinode-japan-ryorishu-cooking-sake-400-ml-90121995"), target: "Japanese cooking-sake bottle" },
    sugar: { file: "sugar.jpg", source: product("/product/fairprice-pure-cane-sugar-fine-grain-3kg-13179180"), target: "White-sugar packet" },
    honey: { file: null, source: search("manuka honey"), target: "Honey bottle or jar" },
    matcha: { file: null, source: product("/product/kirei-premium-100-japan-matcha-tea-powder-30-g-90091862"), target: "Japanese matcha powder packet" },
    milk: { file: null, source: search("Meiji fresh milk"), target: "Fresh milk bottle" },
    ginger: { file: "ginger.jpg", source: product("/product/orgo-fresh-ginger-210-g-90160216"), target: "Fresh ginger root" },
    oil: { file: "oil.png", source: null, target: "Premium bottle of extra virgin olive oil" },
    sesame: { file: "sesame.jpg", source: product("/product/pasar-white-sesame-seed-150g-13218883"), target: "White sesame seed packet" },
    "salmon-fillet": { file: "salmon.jpg", source: product("/product/catch-seafood-atlantic-salmon-fillet-1-3-kg-90122048"), target: "Raw salmon fillet package" },
    salt: { file: "salt.jpg", source: product("/product/fairprice-premium-fine-salt-500g-432823"), target: "Ordinary table-salt packet" },
    eggs: { file: "egg.jpg", source: product("/product/pasar-fresh-eggs-30-per-pack-13197730"), target: "Fresh egg carton" },
    "plain-bee-hoon": { file: "plain-bee-hoon.jpg", source: null, target: "Cooked plain bee hoon with vegetables, wrapped in brown paper" },
    "knorr-quick-serve-macaroni": { file: null, source: product("/product/knorr-chicken-quick-serve-macaroni-bundle-of-4"), target: "Knorr Chicken Quick Serve Macaroni packet" },
    ham: { file: null, source: search("sliced ham"), target: "Ready-to-eat sliced ham" },
    "fresh-chilli": { file: null, source: product("/product/simply-finest-red-chilli-150g-13093893"), target: "Fresh red chillies" },
    "spring-onion": { file: null, source: product("/product/10554146"), target: "Fresh spring onion stalks" },
    onion: { file: null, source: search("fresh onion"), target: "Fresh whole onion" },
    spinach: { file: "spinach.jpg", source: product("/product/kok-fah-baby-spinach-200g-13032623"), target: "Fresh spinach pack" },
    lemon: { file: "lemon.jpg", source: product("/product/freshco-lemons-fresh"), target: "Fresh lemons" },
    pork: { file: "pork.jpg", source: product("/product/simply-yumme-pork-lean-slice"), target: "Lean raw pork slices in a labelled pack" },
    "pork-shoulder": { file: null, source: search("pork shoulder butt"), target: "Pork shoulder butt slices" },
    "pork-loin": { file: null, source: search("pork loin chop"), target: "Thick-cut pork loin chops" },
    cabbage: { file: "cabbage.jpg", source: product("/product/orgo-fresh-cabbage-whole-1-pc-90150967"), target: "Ordinary whole green cabbage" },
    squid: { file: null, source: search("squid"), target: "Cleaned squid in a labelled chilled or frozen pack" },
    "mixed-vegetables": { file: null, source: product("/product/fairprice-mixed-vegetable-1kg-11475941"), target: "Mixed vegetables pack" },
    "shimeji-mushroom": { file: "shimeji-mushroom.jpg", source: product("/product/hokto-mushroom-white-shimeiji-100g-11017131"), target: "Shimeji mushroom retail pack" },
    "button-mushroom": { file: "button-mushroom.jpg", source: product("/product/pasar-white-button-mushroom-200g-13101275"), target: "White button mushroom retail pack" },
    "enoki-mushroom": { file: null, source: product("/product/simply-finest-enoki-mushroom-300g-13092651"), target: "Fresh enoki mushroom pack" },
    dashi: { file: "dashi.jpg", source: product("/product/ajinomoto-hon-dashi-kirei-1-kg-90155858"), target: "Japanese dashi stock packet" },
    tuna: { file: "tuna.jpg", source: product("/product/fairprice-tuna-flakes-in-water-160g-13256630"), target: "Canned tuna in water" },
    tofu: { file: "firm-tofu.jpg", source: product("/product/fairprice-tau-kwa-2s-400g-13233989"), target: "Firm tofu in refrigerated retail packaging" },
    cucumber: { file: "cucumber.jpg", source: product("/product/malaysia-naturally-fresh-japanese-cucumber-400g-13097478"), target: "Fresh Japanese cucumber" },
    "sesame-oil": { file: "sesame-oil.jpg", source: product("/product/lee-kum-kee-pure-sesame-oil-207ml-13160717"), target: "Sesame-oil bottle" },
    "rice-vinegar": { file: "rice-vinegar.jpg", source: product("/product/redman-rice-vinegar"), target: "Rice-vinegar bottle" },
    miso: { file: "miso-paste.jpg", source: product("/product/kirei-yamataka-omiso-ya-san-japanese-shiro-miso-paste-1-kg-90085339"), target: "Japanese miso tub or pouch" },
    water: { file: "water.png", source: null, target: "A clean glass of water" },
    apple: { file: null, source: product("/product/china-fuji-apples-5-per-pack-13198956"), target: "Fresh apple" },
    bread: { file: null, source: product("/product/fairprice-wholemeal-bread-80g-420g-12324272"), target: "Sliced sandwich bread" },
    "peanut-butter": { file: null, source: search("FairPrice creamy peanut butter"), target: "Peanut butter jar" },
    "strawberry-jam": { file: null, source: search("strawberry jam"), target: "Strawberry jam jar" },
    banana: { file: null, source: product("/product/13135270"), target: "Fresh banana" },
    mayonnaise: { file: null, source: search("Kewpie Japanese mayonnaise"), target: "Mayonnaise bottle" },
    dashi: { file: "dashi.jpg", source: product("/product/ajinomoto-hon-dashi-kirei-1-kg-90155858"), target: "Japanese dashi stock packet" },
    tuna: { file: "tuna.jpg", source: product("/product/fairprice-tuna-flakes-in-water-160g-13256630"), target: "Canned tuna in water" },
    tofu: { file: "firm-tofu.jpg", source: product("/product/fairprice-tau-kwa-2s-400g-13233989"), target: "Firm tofu in refrigerated retail packaging" },
    cucumber: { file: "cucumber.jpg", source: product("/product/malaysia-naturally-fresh-japanese-cucumber-400g-13097478"), target: "Fresh Japanese cucumber" },
    "sesame-oil": { file: "sesame-oil.jpg", source: product("/product/lee-kum-kee-pure-sesame-oil-207ml-13160717"), target: "Sesame-oil bottle" },
    "rice-vinegar": { file: "rice-vinegar.jpg", source: product("/product/redman-rice-vinegar"), target: "Rice-vinegar bottle" },
    miso: { file: "miso-paste.jpg", source: product("/product/kirei-yamataka-omiso-ya-san-japanese-shiro-miso-paste-1-kg-90085339"), target: "Japanese miso tub or pouch" },
    water: { file: "water.png", source: null, target: "A clean glass of water" },
    apple: { file: null, source: product("/product/china-fuji-apples-5-per-pack-13198956"), target: "Fresh apple" },
    bread: { file: null, source: product("/product/fairprice-wholemeal-bread-80g-420g-12324272"), target: "Sliced sandwich bread" },
    "peanut-butter": { file: null, source: search("FairPrice creamy peanut butter"), target: "Peanut butter jar" },
    "strawberry-jam": { file: null, source: search("strawberry jam"), target: "Strawberry jam jar" },
    banana: { file: null, source: product("/product/13135270"), target: "Fresh banana" },
    mayonnaise: { file: null, source: search("Kewpie Japanese mayonnaise"), target: "Mayonnaise bottle" },
    flour: { file: null, source: search("plain flour"), target: "Plain wheat flour packet" },
    jam: { file: null, source: search("fruit jam"), target: "Fruit jam jar" },
    macaroni: { file: null, source: product("/product/prego-pasta-macaroni-500g-13083276"), target: "Plain elbow macaroni packet" },
    pasta: { file: null, source: product("/product/fairprice-pasta-spaghetti-500g-13184515"), target: "Plain dried spaghetti or pasta packet" },
    "tomato-ketchup": { file: null, source: product("/product/fairprice-tomato-ketchup-320g-13066243"), target: "Tomato ketchup bottle" },
    "consomme-powder": { file: null, source: search("Ajinomoto chicken consomme powder"), target: "Chicken consommé powder packet or tub" },
    "maitake-mushroom": { file: null, source: product("/product/hokto-maitake-mushroom-100g-13041084"), target: "Fresh maitake mushroom pack" },
    "garlic-paste": { file: null, source: product("/product/13157215"), target: "Garlic-paste jar or tube" },
    "salt-pepper-seasoning": { file: null, source: product("/product/sandb-salt-pepper-ajitsuke-shio-kosho-seasoning"), target: "S&B salt-and-pepper seasoning shaker or refill pack" },
    "pork-ribs": { file: null, source: search("fresh pork ribs"), target: "Raw pork ribs" },
    "bak-kut-teh-spices": { file: null, source: product("/product/song-fa-bak-kut-teh-spices-30g-13190511"), target: "Singapore bak kut teh spice packet" },
    garlic: { file: null, source: search("fresh garlic"), target: "Fresh garlic bulb" },
    "tau-pok": { file: null, source: search("tau pok"), target: "Tau Pok fried tofu puffs in a labelled pack" },
    "garlic-pepper": { file: null, source: search("garlic pepper seasoning"), target: "Garlic pepper seasoning bottle" },
    "potato-starch": { file: null, source: search("Japanese potato starch katakuriko"), target: "Potato starch packet" },
    "dashi-soy-sauce": { file: null, source: product("/product/yamaki-shiro-dashi-bonito-stock-seasoning-500-ml-90045774"), target: "Japanese shiro dashi seasoning bottle" },
    "dark-soy-sauce": { file: null, source: search("dark soy sauce"), target: "Dark soy sauce bottle" },
    nori: { file: null, source: "https://payment.fairprice.com.sg/product/hamaotome-ariake-san-yakinori-10-pcs-sushi-seaweed-sheet-10-pc-90081194", target: "Japanese nori seaweed sheets packet" },
    beef: { file: null, source: search("fresh sliced beef"), target: "Minced beef or sliced beef packet" },
    "crab-stick": { file: null, source: search("Japanese crab sticks surimi"), target: "Crab sticks / surimi package" },
    "wagyu-steak": { file: null, source: search("wagyu steak"), target: "Wagyu steak package (chilled/frozen)" },
    "black-pepper": { file: null, source: search("black pepper grinder"), target: "Black pepper grinder or shaker bottle" },
    potato: { file: null, source: product("/product/holland-potato-china-1kg-13057650"), target: "Fresh whole potatoes" },
    "japanese-curry-blocks": { file: null, source: search("S&B Golden Curry mild"), target: "Japanese curry roux block packet" },
    "king-oyster-mushroom": { file: null, source: product("/product/eloasis-king-oyster-mushroom-300g-13243900"), target: "Fresh king oyster mushroom pack" },
    "cherry-tomatoes": { file: null, source: search("fresh cherry tomatoes"), target: "Fresh cherry tomatoes punnet" },
    "chilli-powder": { file: null, source: search("Japanese ichimi chilli powder"), target: "Chilli powder bottle or shaker" },
    "cooked-protein": { file: "tuna.jpg", source: product("/product/fairprice-tuna-flakes-in-water-160g-13256630"), target: "Cooked meat, fish, or other protein flakes/pieces" },
    "rice-seasoning": { file: null, source: search("Japanese furikake rice seasoning"), target: "Furikake rice seasoning packet" },
    kale: { file: null, source: product("/product/vegeponics-pesticide-free-curly-kale-120-g-90065989"), target: "Fresh kale leaves pack" },
    mushrooms: { file: null, source: product("/product/eloasis-mixed-mushroom-combo-200g-13256463"), target: "Fresh mixed mushrooms" },
    "salmon-or-meat": { file: "salmon.jpg", source: product("/product/catch-seafood-atlantic-salmon-fillet-1-3-kg-90122048"), target: "Raw salmon fillet or sliced beef/pork packet" },
    prawns: { file: null, source: search("fresh prawns"), target: "Fresh whole prawns/shrimps packet" },
    "pork-belly": { file: null, source: search("fresh pork belly"), target: "Raw pork belly block or slices" },
    "lotus-root": { file: "lotus-root.jpg", source: product("/product/mr-fresh-slices-lotus-root-350g-13235036"), target: "Fresh lotus root" },
    "fish-cake": { file: null, source: search("Japanese kamaboko fish cake"), target: "Japanese kamaboko fish cake log" },
    "black-beans": { file: null, source: "https://www.fulamingo.com/products/isshin-kuromame-black-beans", target: "Sweetened black soybeans (kuromame)" },
    "osechi-sides": { file: null, source: "https://www.ristorantetakada.com.sg/news-1-1/limited-to-30-sets-%E2%80%93-celebrate-2026-with-ristorante-takada%E2%80%99s-italian-osechi", target: "Japanese Osechi side-dish assortment" },
    "bamboo-shoots": { file: null, source: search("bamboo shoots"), target: "Fresh or canned bamboo shoots" },
    "osechi-vegetables": { file: "lotus-root.jpg", source: product("/product/mr-fresh-slices-lotus-root-350g-13235036"), target: "Fresh lotus root, carrots, bamboo shoots, and mushrooms mix" }
  });
})();
